language: php
php:
- 5.5
- 5.6
- hhvm
addons:
  code_climate:
    repo_token:
      secure: "ISxHFbuiVRjGSS2gVKxeMARlDk79nZJpkvx9nAR3gG2MX7YXSVpZ+kvBOjTfOLaWZwCnLpXWQ7Ho5bvULNfjaylQA0M7vYKVIfFzztgkYAN4c+8YlRCSZY/Ea3tp+po0wrO3657yaZAA0S6E0n4sUno0YY8G3CyGEa1YwN/n8hs="
before_script:
- make travis-init
script:
- make travis-run
after_success:
- make travis-report

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b5bf3016b30017ac12c9
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
